[package]
name = "countdown-bot-proc-macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0.15"
syn = "1.0.86"

[lib]
proc-macro = true
