name: Build binary

on:
  push:
    tags:
      - v**
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        job:
          - { os: macos-latest }
          - { os: ubuntu-latest }
          - { os: windows-latest }


    name: Build
    runs-on: ${{ matrix.job.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Rename binary
        id: rename
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            BIN='countdown_bot3_linux_amd64'
            mv target/release/app target/release/$BIN
          elif [ "$RUNNER_OS" == "macOS" ]; then
            BIN='countdown_bot3_darwin_amd64'
            mv target/release/app target/release/$BIN
          else
            BIN='countdown_bot3_windows_amd64.exe'
            mv target/release/app.exe target/release/$BIN
          fi
          echo "::set-output name=bin::target/release/$BIN"
      - uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: |
            target/release/countdown_bot3*
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ steps.rename.outputs.bin }}
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
